Repository cyberbotics/webots_ros2, pull requests merged in 2020-08, with the labels that each got.

#120 Various macOS fixes
  webots_ros2/CHANGELOG.rst
  webots_ros2_core/webots_ros2_core/utils.py
  webots_ros2_desktop/setup.py
Labels: bug, enhancement

#123 Prepare `webots_ros2` for release
  webots_ros2_abb/worlds/.abb_irb4600.wbproj
  webots_ros2_abb/worlds/abb_irb4600.wbt
  webots_ros2_demos/worlds/.armed_robots.wbproj
  webots_ros2_demos/worlds/armed_robots.wbt
  webots_ros2_examples/worlds/.ros_example.wbproj
  webots_ros2_examples/worlds/ros_example.wbt
  webots_ros2_tiago/worlds/ros_tiago.wbt
  webots_ros2_universal_robot/worlds/.universal_robot.wbproj
  webots_ros2_universal_robot/worlds/.universal_robot_multiple.wbproj
  webots_ros2_universal_robot/worlds/universal_robot.wbt
  webots_ros2_universal_robot/worlds/universal_robot_multiple.wbt
  webots_ros2_universal_robot/worlds/universal_robot_rviz.wbt
Labels: bug

#126 Update Version and Changelogs
  webots_ros2/package.xml
  webots_ros2/setup.py
  webots_ros2_abb/CHANGELOG.rst
  webots_ros2_abb/package.xml
  webots_ros2_abb/setup.py
  webots_ros2_core/CHANGELOG.rst
  webots_ros2_core/package.xml
  webots_ros2_core/setup.py
  webots_ros2_demos/CHANGELOG.rst
  webots_ros2_demos/package.xml
  webots_ros2_demos/setup.py
  webots_ros2_desktop/CHANGELOG.rst
  webots_ros2_desktop/package.xml
  webots_ros2_desktop/setup.py
  webots_ros2_epuck/CHANGELOG.rst
  webots_ros2_epuck/package.xml
  webots_ros2_epuck/setup.py
  webots_ros2_examples/CHANGELOG.rst
  webots_ros2_examples/package.xml
  webots_ros2_examples/setup.py
  webots_ros2_importer/package.xml
  webots_ros2_importer/setup.py
  webots_ros2_msgs/package.xml
  webots_ros2_tiago/CHANGELOG.srt
  webots_ros2_tiago/package.xml
  webots_ros2_tiago/setup.py
  webots_ros2_universal_robot/CHANGELOG.rst
  webots_ros2_universal_robot/package.xml
  webots_ros2_universal_robot/setup.py
  webots_ros2_ur_e_description/package.xml
  webots_ros2_ur_e_description/setup.py
Labels: enhancement

#127 Fix Classname
  webots_ros2_examples/webots_ros2_examples/khepera_driver.py
Labels: bug

#124 Robotic arm node
  webots_ros2_abb/launch/abb_irb4600.launch.py
  webots_ros2_abb/setup.py
  webots_ros2_abb/webots_ros2_abb/.gitignore
  webots_ros2_abb/webots_ros2_abb/__init__.py
  webots_ros2_abb/webots_ros2_abb/abb_driver.py
  webots_ros2_core/README.md
  webots_ros2_core/setup.py
  webots_ros2_core/webots_ros2_core/devices/robot_device.py
  webots_ros2_core/webots_ros2_core/webots_node.py
  webots_ros2_core/webots_ros2_core/webots_robotic_arm_node.py
  webots_ros2_demos/launch/armed_robots.launch.py
  webots_ros2_demos/webots_ros2_demos/follow_joint_trajectory_client.py
  webots_ros2_universal_robot/launch/universal_robot.launch.py
  webots_ros2_universal_robot/launch/universal_robot_multiple.launch.py
  webots_ros2_universal_robot/launch/universal_robot_rviz.launch.py
  webots_ros2_universal_robot/launch/universal_robot_rviz_dynamic.launch.py
  webots_ros2_universal_robot/resource/view_robot_dynamic.rviz
  webots_ros2_universal_robot/setup.py
  webots_ros2_universal_robot/webots_ros2_universal_robot/.gitignore
  webots_ros2_universal_robot/webots_ros2_universal_robot/__init__.py
  webots_ros2_universal_robot/webots_ros2_universal_robot/universal_robot.py
  webots_ros2_ur_e_description/rviz/view_robot.rviz
Labels: enhancement

#130 Add Github Actions
  .github/workflows/test.yml
  webots_ros2_desktop/setup.py
Labels: enhancement
