Repository cyberbotics/webots_ros2, pull requests merged in 2020-10, with the labels that each got.

#148 Publish PointCloud messages from 3D LiDAR
  webots_ros2_core/webots_ros2_core/devices/device_manager.py
  webots_ros2_core/webots_ros2_core/devices/laser_device.py
  webots_ros2_core/webots_ros2_core/devices/lidar_device.py
  webots_ros2_universal_robot/README.md
  webots_ros2_universal_robot/setup.py
  webots_ros2_universal_robot/worlds/.universal_robot_lidar.wbproj
  webots_ros2_universal_robot/worlds/universal_robot_lidar.wbt
Labels: bug

#156 Update version number to 1.0.2
  webots_ros2/package.xml
  webots_ros2/setup.py
  webots_ros2_abb/package.xml
  webots_ros2_abb/setup.py
  webots_ros2_core/CHANGELOG.rst
  webots_ros2_core/package.xml
  webots_ros2_core/setup.py
  webots_ros2_demos/package.xml
  webots_ros2_demos/setup.py
  webots_ros2_epuck/package.xml
  webots_ros2_epuck/setup.py
  webots_ros2_examples/package.xml
  webots_ros2_examples/setup.py
  webots_ros2_importer/package.xml
  webots_ros2_importer/setup.py
  webots_ros2_msgs/package.xml
  webots_ros2_tiago/package.xml
  webots_ros2_tiago/setup.py
  webots_ros2_universal_robot/package.xml
  webots_ros2_universal_robot/setup.py
  webots_ros2_ur_e_description/package.xml
  webots_ros2_ur_e_description/setup.py
Labels: enhancement

#155 Fix ur_e_description Attribution
  webots_ros2_ur_e_description/README.md
  webots_ros2_ur_e_description/package.xml
Labels: enhancement

#162 Fix webots_ros2_importer
  webots_ros2_importer/webots_ros2_importer/urdf2proto.py
Labels: bug

#161 Improve documentation
  .github/workflows/documentation.yml
  README.md
  docs/.gitignore
  docs/Makefile
  docs/cover.png
  docs/source/API-Devices.rst
  docs/source/API-JointStatePublisher.rst
  docs/source/API-Utils.rst
  docs/source/API-WebotsLauncher.rst
  docs/source/API-WebotsNode.rst
  docs/source/_API-Header.rst
  docs/source/_API-Index.rst
  docs/source/conf.py
  webots_ros2/README.md
  webots_ros2_abb/README.md
  webots_ros2_abb/abb.png
  webots_ros2_core/README.md
  webots_ros2_core/webots_ros2_core/devices/camera_device.py
  webots_ros2_core/webots_ros2_core/devices/distance_sensor_device.py
  webots_ros2_core/webots_ros2_core/devices/imu_device.py
  webots_ros2_core/webots_ros2_core/devices/led_device.py
  webots_ros2_core/webots_ros2_core/devices/lidar_device.py
  webots_ros2_core/webots_ros2_core/devices/light_sensor_device.py
  webots_ros2_core/webots_ros2_core/devices/robot_device.py
  webots_ros2_core/webots_ros2_core/joint_state_publisher.py
  webots_ros2_core/webots_ros2_core/utils.py
  webots_ros2_core/webots_ros2_core/webots_differential_drive_node.py
  webots_ros2_core/webots_ros2_core/webots_node.py
  webots_ros2_core/webots_ros2_core/webots_robotic_arm_node.py
  webots_ros2_demos/README.md
  webots_ros2_epuck/EPUCK_ROS2.md
  webots_ros2_epuck/README.md
  webots_ros2_examples/README.md
  webots_ros2_examples/assets/khepera4.png
  webots_ros2_examples/assets/ros_example.png
  webots_ros2_examples/assets/turtlebot3_burger.png
  webots_ros2_importer/README.md
  webots_ros2_msgs/README.md
  webots_ros2_tiago/README.md
  webots_ros2_universal_robot/README.md
  webots_ros2_universal_robot/assets/universal_robot.png
  webots_ros2_universal_robot/assets/universal_robot_multiple.png
Labels: documentation
