Repository cyberbotics/webots_ros2, pull requests merged in 2020-04, with the labels that each got.

#59 Create e-puck2 driver
  webots_ros2_core/webots_ros2_core/math_utils.py
  webots_ros2_core/webots_ros2_core/webots_node.py
  webots_ros2_epuck/CHANGELOG.rst
  webots_ros2_epuck/README.md
  webots_ros2_epuck/assets/ground_sensors_webots.png
  webots_ros2_epuck/launch/example_launch.py
  webots_ros2_epuck/package.xml
  webots_ros2_epuck/resource/all.rviz
  webots_ros2_epuck/resource/webots_ros2_epuck
  webots_ros2_epuck/setup.cfg
  webots_ros2_epuck/setup.py
  webots_ros2_epuck/test/test_copyright.py
  webots_ros2_epuck/test/test_flake8.py
  webots_ros2_epuck/test/test_pep257.py
  webots_ros2_epuck/webots_ros2_epuck/.gitignore
  webots_ros2_epuck/webots_ros2_epuck/__init__.py
  webots_ros2_epuck/webots_ros2_epuck/drive_calibrator.py
  webots_ros2_epuck/webots_ros2_epuck/driver.py
  webots_ros2_epuck/worlds/.epuck_world.wbproj
  webots_ros2_epuck/worlds/epuck_world.wbt
Labels: enhancement

#61 Add Reusable Differential Drive Node
  .gitignore
  webots_ros2_core/CHANGELOG.rst
  webots_ros2_core/webots_ros2_core/webots_differential_drive_node.py
  webots_ros2_epuck/README.md
  webots_ros2_epuck/test/test_flake8.py
  webots_ros2_epuck/webots_ros2_epuck/driver.py
  webots_ros2_tiago/README.md
  webots_ros2_tiago/launch/tiago.launch.py
  webots_ros2_tiago/package.xml
  webots_ros2_tiago/resource/odometry.rviz
  webots_ros2_tiago/setup.py
  webots_ros2_tiago/test/test_flake8.py
  webots_ros2_tiago/webots_ros2_tiago/tiago_controller.py
Labels: enhancement

#68 Improve Support for Differential Drive Calibration
  webots_ros2_epuck/README.md
  webots_ros2_epuck/webots_ros2_epuck/drive_calibrator.py
Labels: enhancement

#74 Replace .now() method
  webots_ros2_core/test/test_flake8.py
  webots_ros2_core/webots_ros2_core/joint_state_publisher.py
  webots_ros2_core/webots_ros2_core/laser_publisher.py
  webots_ros2_core/webots_ros2_core/tf_publisher.py
  webots_ros2_core/webots_ros2_core/trajectory_follower.py
  webots_ros2_core/webots_ros2_core/webots_node.py
  webots_ros2_demos/webots_ros2_demos/follow_joint_trajectory_client.py
  webots_ros2_epuck/webots_ros2_epuck/driver.py
Labels: bug

#69 Separate Common and Webots Specific Documentation for e-puck
  webots_ros2_epuck/EPUCK_ROS2.md
  webots_ros2_epuck/README.md
  webots_ros2_epuck/assets/sensors_and_leds.png
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_epuck/launch/robot_tools_launch.py
  webots_ros2_epuck/launch/robot_with_tools_launch.py
  webots_ros2_epuck/setup.py
Labels: documentation

#75 Cleanup Unused Function
  webots_ros2_core/webots_ros2_core/trajectory_follower.py
Labels: bug

#77 Add Generic Differential Drive Node
  webots_ros2_core/setup.py
  webots_ros2_core/webots_ros2_core/webots_differential_drive_node.py
  webots_ros2_tiago/launch/tiago.launch.py
  webots_ros2_tiago/setup.py
  webots_ros2_tiago/webots_ros2_tiago/.gitignore
  webots_ros2_tiago/webots_ros2_tiago/__init__.py
  webots_ros2_tiago/webots_ros2_tiago/tiago_controller.py
Labels: enhancement
