Repository cyberbotics/webots_ros2, pull requests merged in 2021-06, with the labels that each got.

#228 Add missing dependency to TurtleBot3 Burger
  webots_ros2_turtlebot/package.xml
  webots_ros2_turtlebot/resource/ros2control.yml
Labels: bug

#236 Add controller manager spawner to the TurtleBot launch file
  webots_ros2_turtlebot/launch/robot_launch.py
Labels: enhancement

#238 Increase version and add documentation
  webots_ros2/package.xml
  webots_ros2/setup.py
  webots_ros2_abb/package.xml
  webots_ros2_abb/setup.py
  webots_ros2_control/package.xml
  webots_ros2_core/package.xml
  webots_ros2_core/setup.py
  webots_ros2_demos/package.xml
  webots_ros2_demos/setup.py
  webots_ros2_driver/README.md
  webots_ros2_driver/package.xml
  webots_ros2_epuck/package.xml
  webots_ros2_epuck/setup.py
  webots_ros2_examples/package.xml
  webots_ros2_examples/setup.py
  webots_ros2_importer/package.xml
  webots_ros2_importer/setup.py
  webots_ros2_msgs/package.xml
  webots_ros2_tesla/package.xml
  webots_ros2_tesla/setup.py
  webots_ros2_tiago/package.xml
  webots_ros2_tiago/setup.py
  webots_ros2_turtlebot/package.xml
  webots_ros2_turtlebot/setup.py
  webots_ros2_tutorials/package.xml
  webots_ros2_tutorials/setup.py
  webots_ros2_universal_robot/package.xml
  webots_ros2_universal_robot/setup.py
  webots_ros2_ur_e_description/package.xml
  webots_ros2_ur_e_description/setup.py
Labels: documentation

#233 fixed URLS
  webots_ros2_epuck/protos/E-puckDistanceSensor_enu.proto
  webots_ros2_epuck/protos/E-puck_enu.proto
  webots_ros2_epuck/protos/LegoTallInterval.proto
  webots_ros2_epuck/protos/LegoTallWall.proto
  webots_ros2_epuck/protos/icons/E-puck.png
  webots_ros2_epuck/protos/icons/E-puckDistanceSensor.png
  webots_ros2_epuck/protos/icons/E-puckGroundSensors.png
  webots_ros2_epuck/protos/textures/e-puck1_plate_base_color.jpg
  webots_ros2_epuck/protos/textures/e-puck1_plate_metalness.jpg
  webots_ros2_epuck/protos/textures/e-puck1_plate_normal.jpg
  webots_ros2_epuck/protos/textures/e-puck1_plate_occlusion.jpg
  webots_ros2_epuck/protos/textures/e-puck1_plate_roughness.jpg
  webots_ros2_epuck/protos/textures/e-puck1_turret_base_color.jpg
  webots_ros2_epuck/protos/textures/e-puck1_turret_metalness.jpg
  webots_ros2_epuck/protos/textures/e-puck1_turret_normal.jpg
  webots_ros2_epuck/protos/textures/e-puck1_turret_occlusion.jpg
  webots_ros2_epuck/protos/textures/e-puck1_turret_roughness.jpg
  webots_ros2_epuck/protos/textures/e-puck2_plate.jpg
  webots_ros2_epuck/protos/textures/e-puck2_plate_metalness.jpg
  webots_ros2_epuck/protos/textures/e-puck2_plate_normal.jpg
  webots_ros2_epuck/protos/textures/e-puck2_plate_occlusion.jpg
  webots_ros2_epuck/protos/textures/e-puck2_plate_roughness.jpg
  webots_ros2_epuck/protos/textures/gctronic_logo.png
  webots_ros2_epuck/protos/textures/raspberry_pi_bottom.jpg
  webots_ros2_epuck/protos/textures/raspberry_pi_top_base_color.jpg
  webots_ros2_epuck/protos/textures/raspberry_pi_top_normal.jpg
  webots_ros2_epuck/protos/textures/raspberry_pi_top_occlusion.jpg
  webots_ros2_epuck/setup.py
  webots_ros2_examples/protos/Khepera4_enu.proto
  webots_ros2_examples/protos/textures/khepera4_bottom_base_color.jpg
  webots_ros2_examples/protos/textures/khepera4_bottom_metalness.jpg
  webots_ros2_examples/protos/textures/khepera4_bottom_normal.jpg
  webots_ros2_examples/protos/textures/khepera4_bottom_occlusion.jpg
  webots_ros2_examples/protos/textures/khepera4_bottom_roughness.jpg
  webots_ros2_examples/protos/textures/khepera4_left_sticker.png
  webots_ros2_examples/protos/textures/khepera4_right_sticker.png
  webots_ros2_examples/protos/textures/khepera4_top_base_color.jpg
  webots_ros2_examples/protos/textures/khepera4_top_normal.jpg
  webots_ros2_examples/protos/textures/khepera4_top_occlusion.jpg
  webots_ros2_examples/protos/textures/khepera4_top_roughness.jpg
  webots_ros2_examples/setup.py
  webots_ros2_tesla/setup.py
  webots_ros2_tesla/worlds/tesla_world.wbt
  webots_ros2_tesla/worlds/textures/ground.jpg
  webots_ros2_turtlebot/setup.py
  webots_ros2_universal_robot/setup.py
  webots_ros2_universal_robot/worlds/textures/ur5e_normal_0.jpg
  webots_ros2_universal_robot/worlds/textures/ur5e_normal_1.jpg
  webots_ros2_universal_robot/worlds/textures/ur5e_normal_2.jpg
  webots_ros2_universal_robot/worlds/textures/ur5e_normal_3.jpg
  webots_ros2_universal_robot/worlds/textures/ur5e_normal_4.jpg
  webots_ros2_universal_robot/worlds/textures/ur5e_normal_5.jpg
  webots_ros2_universal_robot/worlds/textures/ur5e_occlusion_0.jpg
  webots_ros2_universal_robot/worlds/textures/ur5e_occlusion_1.jpg
  webots_ros2_universal_robot/worlds/textures/ur5e_occlusion_2.jpg
  webots_ros2_universal_robot/worlds/textures/ur5e_occlusion_3.jpg
  webots_ros2_universal_robot/worlds/textures/ur5e_occlusion_4.jpg
  webots_ros2_universal_robot/worlds/textures/ur5e_occlusion_5.jpg
Labels: enhancement
