Repository cyberbotics/webots_ros2, pull requests merged in 2021-08, with the labels that each got.

#259 Update badges
  README.md
Labels: documentation

#262 Fix the IMU library exportation
  webots_ros2_driver/CMakeLists.txt
Labels: bug

#264 Prepare version number for 1.1.1
  .travis.yml
  scripts/version_increase.bash
  webots_ros2/package.xml
  webots_ros2/setup.py
  webots_ros2_abb/package.xml
  webots_ros2_abb/setup.py
  webots_ros2_control/CMakeLists.txt
  webots_ros2_control/package.xml
  webots_ros2_core/package.xml
  webots_ros2_core/setup.py
  webots_ros2_demos/package.xml
  webots_ros2_demos/setup.py
  webots_ros2_driver/package.xml
  webots_ros2_epuck/package.xml
  webots_ros2_epuck/setup.py
  webots_ros2_examples/package.xml
  webots_ros2_examples/setup.py
  webots_ros2_importer/package.xml
  webots_ros2_importer/setup.py
  webots_ros2_mavic/package.xml
  webots_ros2_mavic/setup.py
  webots_ros2_msgs/package.xml
  webots_ros2_tesla/package.xml
  webots_ros2_tesla/setup.py
  webots_ros2_tiago/package.xml
  webots_ros2_tiago/setup.py
  webots_ros2_turtlebot/package.xml
  webots_ros2_turtlebot/setup.py
  webots_ros2_tutorials/package.xml
  webots_ros2_tutorials/setup.py
  webots_ros2_universal_robot/package.xml
  webots_ros2_universal_robot/setup.py
  webots_ros2_ur_e_description/package.xml
  webots_ros2_ur_e_description/setup.py
Labels: enhancement

#263 Use ros2 node clock for message timestamping
  webots_ros2_driver/src/plugins/dynamic/Ros2IMU.cpp
  webots_ros2_driver/src/plugins/static/Ros2Camera.cpp
  webots_ros2_driver/src/plugins/static/Ros2DistanceSensor.cpp
  webots_ros2_driver/src/plugins/static/Ros2GPS.cpp
  webots_ros2_driver/src/plugins/static/Ros2Lidar.cpp
  webots_ros2_driver/src/plugins/static/Ros2LightSensor.cpp
  webots_ros2_driver/src/plugins/static/Ros2RangeFinder.cpp
  webots_ros2_turtlebot/launch/robot_launch.py
Labels: bug

#266 Fix Rolling warnings and `ament_python_install_package`
  .github/workflows/test.yml
  webots_ros2/setup.cfg
  webots_ros2_abb/setup.cfg
  webots_ros2_core/setup.cfg
  webots_ros2_demos/setup.cfg
  webots_ros2_driver/CMakeLists.txt
  webots_ros2_driver/src/PythonPlugin.cpp
  webots_ros2_epuck/setup.cfg
  webots_ros2_examples/setup.cfg
  webots_ros2_importer/setup.cfg
  webots_ros2_mavic/setup.cfg
  webots_ros2_tesla/setup.cfg
  webots_ros2_tiago/setup.cfg
  webots_ros2_turtlebot/setup.cfg
  webots_ros2_turtlebot/webots_ros2_turtlebot/plugin_example.py
  webots_ros2_tutorials/setup.cfg
  webots_ros2_universal_robot/setup.cfg
  webots_ros2_ur_e_description/setup.cfg
Labels: bug

#283 Print tips: robot_state_publisher started or not
  webots_ros2_driver/src/WebotsNode.cpp
Labels: enhancement

#285 Revert `robot_state_publisher` check
  webots_ros2_driver/src/WebotsNode.cpp
Labels: bug

#269 Utilize `webots_ros2_driver` in `webots_ros2_mavic` and `webots_ros2_turtlebot`
  .github/workflows/test.yml
  scripts/ci_after_init.bash
  scripts/ci_before_init_embed.bash
  webots_ros2_mavic/launch/robot_launch.py
  webots_ros2_mavic/resource/mavic_webots.urdf
  webots_ros2_mavic/setup.py
  webots_ros2_mavic/webots_ros2_mavic/mavic_driver.py
  webots_ros2_tests/package.xml
  webots_ros2_tests/test/test_system_driver.py
  webots_ros2_tests/test/test_system_mavic.py
  webots_ros2_tests/test/test_system_turtlebot.py
  webots_ros2_tests/webots_ros2_tests/utils.py
  webots_ros2_turtlebot/launch/robot_launch.py
  webots_ros2_turtlebot/package.xml
  webots_ros2_turtlebot/setup.py
  webots_ros2_turtlebot/worlds/turtlebot3_burger_example.wbt
Labels: enhancement
