Repository cyberbotics/webots_ros2, pull requests merged in 2021-07, with the labels that each got.

#244 update to R2021b
  webots_ros2_epuck/protos/E-puck_enu.proto
  webots_ros2_epuck/protos/LegoTallInterval.proto
  webots_ros2_epuck/protos/LegoTallWall.proto
  webots_ros2_examples/protos/Khepera4_enu.proto
  webots_ros2_tesla/worlds/tesla_world.wbt
Labels: enhancement

#252 Fix Mavic version
  webots_ros2_mavic/package.xml
Labels: bug

#254 Fix library directory
  webots_ros2_driver/CMakeLists.txt
Labels: bug

#255 Fix warnings
  webots_ros2_control/src/Ros2Control.cpp
  webots_ros2_tiago/worlds/ros_tiago.wbt
  webots_ros2_turtlebot/worlds/turtlebot3_burger_example.wbt
Labels: cleanup
