Repository cyberbotics/webots_ros2, pull requests merged in 2022-11, with the labels that each got.

#502 Enhancement: allow world reset on every samples
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_mavic/launch/robot_launch.py
  webots_ros2_tesla/launch/robot_launch.py
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_turtlebot/launch/robot_launch.py
Labels: enhancement

#525 Remove deprecared `webots_ros2_core` package
  README.md
  docs/.gitignore
  docs/Makefile
  docs/source/API-Devices.rst
  docs/source/API-JointStatePublisher.rst
  docs/source/API-Utils.rst
  docs/source/API-WebotsLauncher.rst
  docs/source/API-WebotsNode.rst
  docs/source/_API-Header.rst
  docs/source/_API-Index.rst
  docs/source/conf.py
  images/cover.png
  webots_ros2/CHANGELOG.rst
  webots_ros2/package.xml
  webots_ros2_core/CHANGELOG.rst
  webots_ros2_core/README.md
  webots_ros2_core/launch/robot_launch.py
  webots_ros2_core/package.xml
  webots_ros2_core/resource/webots_ros2_core
  webots_ros2_core/setup.cfg
  webots_ros2_core/setup.py
  webots_ros2_core/test/test_copyright.py
  webots_ros2_core/test/test_flake8.py
  webots_ros2_core/test/test_math_utils.py
  webots_ros2_core/test/test_pep257.py
  webots_ros2_core/webots_ros2_core/.gitignore
  webots_ros2_core/webots_ros2_core/__init__.py
  webots_ros2_core/webots_ros2_core/devices/__init__.py
  webots_ros2_core/webots_ros2_core/devices/camera_device.py
  webots_ros2_core/webots_ros2_core/devices/device.py
  webots_ros2_core/webots_ros2_core/devices/device_manager.py
  webots_ros2_core/webots_ros2_core/devices/distance_sensor_device.py
  webots_ros2_core/webots_ros2_core/devices/gps_device.py
  webots_ros2_core/webots_ros2_core/devices/imu_device.py
  webots_ros2_core/webots_ros2_core/devices/led_device.py
  webots_ros2_core/webots_ros2_core/devices/lidar_device.py
  webots_ros2_core/webots_ros2_core/devices/light_sensor_device.py
  webots_ros2_core/webots_ros2_core/devices/range_finder_device.py
  webots_ros2_core/webots_ros2_core/devices/robot_device.py
  webots_ros2_core/webots_ros2_core/devices/sensor_device.py
  webots_ros2_core/webots_ros2_core/joint_state_publisher.py
  webots_ros2_core/webots_ros2_core/math/README.md
  webots_ros2_core/webots_ros2_core/math/__init__.py
  webots_ros2_core/webots_ros2_core/math/interpolation.py
  webots_ros2_core/webots_ros2_core/math/quaternions.py
  webots_ros2_core/webots_ros2_core/trajectory_follower.py
  webots_ros2_core/webots_ros2_core/utils.py
  webots_ros2_core/webots_ros2_core/webots/__init__.py
  webots_ros2_core/webots_ros2_core/webots/controller.py
  webots_ros2_core/webots_ros2_core/webots/vehicle.py
  webots_ros2_core/webots_ros2_core/webots_differential_drive_node.py
  webots_ros2_core/webots_ros2_core/webots_launcher.py
  webots_ros2_core/webots_ros2_core/webots_node.py
  webots_ros2_core/webots_ros2_core/webots_robotic_arm_node.py
  webots_ros2_driver/README.md
Labels: cleanup

#536 Upgrade to R2023a (master)
  scripts/ci_before_init_embed.bash
Labels: enhancement

#542 Merge master into develop
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
Labels: synchronization
