Repository cyberbotics/webots_ros2, pull requests merged in 2022-10, with the labels that each got.

#481 Replace Windows compatibility with WSL
  webots_ros2_driver/webots_ros2_driver/urdf_spawner.py
  webots_ros2_driver/webots_ros2_driver/utils.py
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_mavic/launch/robot_launch.py
  webots_ros2_tesla/launch/robot_launch.py
  webots_ros2_tests/test/test_system_driver.py
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_turtlebot/launch/robot_launch.py
  webots_ros2_universal_robot/launch/multirobot_launch.py
  webots_ros2_universal_robot/launch/robot_launch/robot_nodes_launch.py
Labels: enhancement

#484 Restore windows compatibility and update deprecation message
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
Labels: bug

#489 Fix relative PROTO not being found
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
Labels: bug

#487 Automatic libcontroller sync
  .github/workflows/libcontroller_updater.yml
Labels: enhancement

#493 Adjust nightly timings and concurrency
  .github/workflows/libcontroller_updater.yml
  .github/workflows/test.yml
  .github/workflows/test_develop.yml
Labels: enhancement

#495 Restore relative url fix
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
Labels: enhancement

#497 Merge `master` into `develop`
  .github/workflows/libcontroller_updater.yml
  .github/workflows/test.yml
  .github/workflows/test_develop.yml
  webots_ros2/package.xml
  webots_ros2/setup.py
  webots_ros2_control/package.xml
  webots_ros2_core/package.xml
  webots_ros2_core/setup.py
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/package.xml
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
  webots_ros2_epuck/CHANGELOG.rst
  webots_ros2_epuck/package.xml
  webots_ros2_epuck/setup.py
  webots_ros2_importer/package.xml
  webots_ros2_importer/setup.py
  webots_ros2_mavic/CHANGELOG.rst
  webots_ros2_mavic/package.xml
  webots_ros2_mavic/setup.py
  webots_ros2_msgs/package.xml
  webots_ros2_tesla/CHANGELOG.rst
  webots_ros2_tesla/package.xml
  webots_ros2_tesla/setup.py
  webots_ros2_tests/package.xml
  webots_ros2_tests/setup.py
  webots_ros2_tiago/CHANGELOG.rst
  webots_ros2_tiago/package.xml
  webots_ros2_tiago/setup.py
  webots_ros2_turtlebot/CHANGELOG.rst
  webots_ros2_turtlebot/package.xml
  webots_ros2_turtlebot/setup.py
  webots_ros2_universal_robot/CHANGELOG.rst
  webots_ros2_universal_robot/package.xml
  webots_ros2_universal_robot/setup.py
Labels: synchronization

#499 Update link to wiki page in README.md
  README.md
Labels: documentation

#485 Add macOS compatibility
  webots_ros2_driver/CMakeLists.txt
  webots_ros2_driver/scripts/webots_tcp_client.py
  webots_ros2_driver/webots_ros2_driver/urdf_spawner.py
  webots_ros2_driver/webots_ros2_driver/utils.py
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_mavic/launch/robot_launch.py
  webots_ros2_tesla/launch/robot_launch.py
  webots_ros2_tests/test/test_system_driver.py
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_turtlebot/launch/robot_launch.py
  webots_ros2_universal_robot/launch/multirobot_launch.py
  webots_ros2_universal_robot/launch/robot_launch/robot_nodes_launch.py
  webots_ros2_universal_robot/resource/robotiq/robotiq_3f_gripper_visualization/cfg/robotiq-3f-gripper_articulated_macro.xacro
  webots_ros2_universal_robot/resource/robotiq/robotiq_3f_gripper_visualization/cfg/robotiq-3f-gripper_finger_articulated_macro.xacro
Labels: enhancement

#500 Merge develop into master
  webots_ros2_driver/CMakeLists.txt
  webots_ros2_driver/scripts/webots_tcp_client.py
  webots_ros2_driver/webots_ros2_driver/ros2_supervisor.py
  webots_ros2_driver/webots_ros2_driver/urdf_spawner.py
  webots_ros2_driver/webots_ros2_driver/utils.py
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_mavic/launch/robot_launch.py
  webots_ros2_tesla/launch/robot_launch.py
  webots_ros2_tests/test/test_system_driver.py
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_turtlebot/launch/robot_launch.py
  webots_ros2_universal_robot/launch/multirobot_launch.py
  webots_ros2_universal_robot/launch/robot_launch/robot_nodes_launch.py
  webots_ros2_universal_robot/resource/robotiq/robotiq_3f_gripper_visualization/cfg/robotiq-3f-gripper_articulated_macro.xacro
  webots_ros2_universal_robot/resource/robotiq/robotiq_3f_gripper_visualization/cfg/robotiq-3f-gripper_finger_articulated_macro.xacro
Labels: synchronization
