Repository cyberbotics/webots_ros2, pull requests merged in 2023-03, with the labels that each got.

#649 Fix develop branch
  scripts/sync_controller_lib.sh
Labels: bug

#648 Merge master into develop
  scripts/ci_after_init.bash
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/webots_ros2_driver/ros2_supervisor.py
  webots_ros2_driver/webots_ros2_driver/utils.py
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
  webots_ros2_epuck/resource/ros2_control.yml
  webots_ros2_mavic/webots_ros2_mavic/mavic_driver.py
  webots_ros2_tests/test/test_system_epuck_with_tools.py
  webots_ros2_tests/test/test_system_tiago.py
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_tiago/resource/ros2_control.yml
  webots_ros2_turtlebot/resource/ros2control.yml
Labels: synchronization, test sources

#645 Replace SLAM toolbox by Cartographer in TIAGo example
  webots_ros2/CHANGELOG.rst
  webots_ros2_tiago/CHANGELOG.rst
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_tiago/resource/cartographer.lua
  webots_ros2_tiago/setup.py
Labels: bug, enhancement, test sources

#642 Improve Tiago navigation
  webots_ros2/CHANGELOG.rst
  webots_ros2_tests/CHANGELOG.rst
  webots_ros2_tests/test/test_system_tiago.py
  webots_ros2_tiago/CHANGELOG.rst
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_tiago/resource/cartographer.lua
  webots_ros2_tiago/resource/nav2_params.yaml
  webots_ros2_tiago/setup.py
Labels: enhancement, cleanup, test sources

#664 adding functionally to copy a sumo network to the tmp folder with the right name
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
Labels: enhancement

#674 get default lidar updateRate from .proto
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/src/plugins/static/Ros2Lidar.cpp
Labels: test sources

#676 Calibrate Tiago odometry and restore SLAM-Toolbox
  webots_ros2/CHANGELOG.rst
  webots_ros2_tiago/CHANGELOG.rst
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_tiago/resource/ros2_control.yml
  webots_ros2_tiago/resource/slam_toolbox_params.yaml
  webots_ros2_tiago/setup.py
Labels: test sources

#683 Fix turtlebot test and improve example
  webots_ros2/CHANGELOG.rst
  webots_ros2_tests/CHANGELOG.rst
  webots_ros2_tests/test/test_system_turtlebot_tutorial_navigation.py
  webots_ros2_turtlebot/CHANGELOG.rst
  webots_ros2_turtlebot/launch/robot_launch.py
  webots_ros2_turtlebot/resource/nav2_params.yaml
  webots_ros2_turtlebot/setup.py
Labels: bug, enhancement, test sources

#686 Fix turtlebot slam test
  webots_ros2/CHANGELOG.rst
  webots_ros2_tests/CHANGELOG.rst
  webots_ros2_tests/test/test_system_turtlebot_tutorial_slam.py
  webots_ros2_turtlebot/CHANGELOG.rst
  webots_ros2_turtlebot/launch/robot_launch.py
Labels: bug, enhancement, test sources

#689 Cleaner ros2_control parameters
  webots_ros2_tiago/resource/ros2_control.yml
  webots_ros2_turtlebot/resource/ros2control.yml
Labels: cleanup

#677 Adding Compass node
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/CMakeLists.txt
  webots_ros2_driver/include/webots_ros2_driver/plugins/static/Ros2Compass.hpp
  webots_ros2_driver/src/WebotsNode.cpp
  webots_ros2_driver/src/plugins/static/Ros2Compass.cpp
  webots_ros2_msgs/CMakeLists.txt
  webots_ros2_msgs/msg/FloatStamped.msg
Labels: enhancement, test sources
