Repository cyberbotics/webots_ros2, pull requests merged in 2023-06, with the labels that each got.

#761 749 ros2camera publishes non canonical topics and camera info
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/src/plugins/static/Ros2Camera.cpp
  webots_ros2_driver/src/plugins/static/Ros2RangeFinder.cpp
  webots_ros2_tesla/webots_ros2_tesla/lane_follower.py
  webots_ros2_tests/test/test_system_driver.py
  webots_ros2_tests/test/test_system_epuck.py
  webots_ros2_tests/test/test_system_tesla.py
Labels: enhancement

#760 Add Iron tests
  .github/workflows/test.yml
  .github/workflows/test_develop.yml
  webots_ros2/CHANGELOG.rst
  webots_ros2_epuck/CHANGELOG.rst
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_epuck/launch/robot_tools_launch.py
  webots_ros2_epuck/resource/all.rviz
  webots_ros2_epuck/resource/nav2_params_iron.yaml
  webots_ros2_epuck/setup.py
  webots_ros2_tests/CHANGELOG.rst
  webots_ros2_tests/test/test_system_turtlebot_tutorial_navigation.py
  webots_ros2_tests/test/test_system_turtlebot_tutorial_slam.py
  webots_ros2_tiago/CHANGELOG.rst
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_tiago/resource/nav2_params_iron.yaml
  webots_ros2_tiago/setup.py
Labels: enhancement

#764 Cleanup simulation reset in launch files
  webots_ros2/CHANGELOG.rst
  webots_ros2_epuck/CHANGELOG.rst
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_mavic/CHANGELOG.rst
  webots_ros2_mavic/launch/robot_launch.py
  webots_ros2_tesla/CHANGELOG.rst
  webots_ros2_tesla/launch/robot_launch.py
  webots_ros2_tiago/CHANGELOG.rst
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_turtlebot/CHANGELOG.rst
  webots_ros2_turtlebot/launch/robot_launch.py
  webots_ros2_universal_robot/CHANGELOG.rst
  webots_ros2_universal_robot/launch/multirobot_launch.py
Labels: bug, cleanup

#771 Adding VacuumGripper device
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/CMakeLists.txt
  webots_ros2_driver/include/webots_ros2_driver/plugins/static/Ros2VacuumGripper.hpp
  webots_ros2_driver/src/WebotsNode.cpp
  webots_ros2_driver/src/plugins/static/Ros2VacuumGripper.cpp
  webots_ros2_msgs/CHANGELOG.rst
  webots_ros2_msgs/CMakeLists.txt
  webots_ros2_msgs/msg/BoolStamped.msg
  webots_ros2_msgs/srv/GetBool.srv
Labels: enhancement, test sources

#768 Fix universal robot interpolation
  webots_ros2/CHANGELOG.rst
  webots_ros2_universal_robot/CHANGELOG.rst
  webots_ros2_universal_robot/resource/Universal_Robots_ROS2_Driver/ur_description/urdf/inc/ur_common.xacro
  webots_ros2_universal_robot/resource/Universal_Robots_ROS2_Driver/ur_description/urdf/ur.urdf.xacro
  webots_ros2_universal_robot/resource/ros2_control_abb_config.yaml
  webots_ros2_universal_robot/resource/ros2_control_config.yaml
  webots_ros2_universal_robot/webots_ros2_universal_robot/follow_joint_trajectory_client.py
  webots_ros2_universal_robot/worlds/robotic_arms.wbt
Labels: bug

#767 Add Ros2Pen static plugin
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/CMakeLists.txt
  webots_ros2_driver/include/webots_ros2_driver/plugins/static/Ros2Pen.hpp
  webots_ros2_driver/src/WebotsNode.cpp
  webots_ros2_driver/src/plugins/static/Ros2Pen.cpp
  webots_ros2_msgs/CHANGELOG.rst
  webots_ros2_msgs/CMakeLists.txt
  webots_ros2_msgs/msg/PenInkProperties.msg
Labels: enhancement

#787 Fix README.md
  README.md
Labels: documentation, cleanup

#793 Fix ros2 control hardware interface API update
  webots_ros2/CHANGELOG.rst
  webots_ros2_control/CHANGELOG.rst
  webots_ros2_control/src/Ros2Control.cpp
Labels: bug

#794 Fix warnings for 2023.1.0
  webots_ros2_epuck/worlds/epuck_world.wbt
  webots_ros2_epuck/worlds/rats_life_benchmark.wbt
  webots_ros2_mavic/worlds/mavic_world.wbt
  webots_ros2_tesla/worlds/tesla_world.wbt
  webots_ros2_tests/worlds/driver_test.wbt
  webots_ros2_tiago/worlds/default.wbt
  webots_ros2_tiago/worlds/default_bringup.wbt
  webots_ros2_turtlebot/resource/ros2control.yml
  webots_ros2_turtlebot/worlds/turtlebot3_burger_example.wbt
  webots_ros2_universal_robot/worlds/robotic_arms.wbt
  webots_ros2_universal_robot/worlds/universal_robot.wbt
Labels: bug

#803 Fix world links on develop
  webots_ros2_epuck/worlds/epuck_world.wbt
  webots_ros2_epuck/worlds/rats_life_benchmark.wbt
  webots_ros2_mavic/worlds/mavic_world.wbt
  webots_ros2_tesla/worlds/tesla_world.wbt
  webots_ros2_tests/worlds/driver_test.wbt
  webots_ros2_tiago/worlds/default.wbt
  webots_ros2_tiago/worlds/default_bringup.wbt
  webots_ros2_turtlebot/worlds/turtlebot3_burger_example.wbt
  webots_ros2_universal_robot/worlds/robotic_arms.wbt
  webots_ros2_universal_robot/worlds/universal_robot.wbt
Labels: cleanup
