Repository cyberbotics/webots_ros2, pull requests merged in 2023-04, with the labels that each got.

#696 Fix Emitter and Receiver devices
  webots_ros2_driver/include/webots_ros2_driver/plugins/static/Ros2Emitter.hpp
  webots_ros2_driver/include/webots_ros2_driver/plugins/static/Ros2Receiver.hpp
  webots_ros2_driver/src/plugins/static/Ros2Emitter.cpp
  webots_ros2_driver/src/plugins/static/Ros2Receiver.cpp
  webots_ros2_msgs/CMakeLists.txt
  webots_ros2_msgs/srv/EmitterSendString.srv
  webots_ros2_msgs/srv/GetFloat.srv
  webots_ros2_msgs/srv/GetInt.srv
  webots_ros2_msgs/srv/ReceiverGetEmitterDirection.srv
  webots_ros2_msgs/srv/SetFloat.srv
  webots_ros2_msgs/srv/SetInt.srv
Labels: cleanup, test sources

#706 Fix CI tests
  scripts/ci_after_init.bash
  scripts/ci_before_init_embed.bash
Labels: bug, test sources

#695 Fix and cleanup e-puck example
  webots_ros2/CHANGELOG.rst
  webots_ros2_epuck/CHANGELOG.rst
  webots_ros2_epuck/launch/rats_life_launch.py
  webots_ros2_epuck/launch/rats_life_waypoints_launch.py
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_epuck/launch/robot_tools_launch.py
  webots_ros2_epuck/launch/robot_with_tools_launch.py
  webots_ros2_epuck/resource/nav2_params.yaml
  webots_ros2_epuck/resource/nav2_rats_life_waypoints.yaml
  webots_ros2_epuck/resource/ros2_control.yml
  webots_ros2_epuck/setup.py
  webots_ros2_tests/CHANGELOG.rst
  webots_ros2_tests/test/test_system_epuck_with_tools.py
  webots_ros2_tests/test/test_system_tiago.py
  webots_ros2_tests/test/test_system_turtlebot_tutorial_navigation.py
  webots_ros2_tests/test/test_system_turtlebot_tutorial_slam.py
Labels: bug, cleanup, test sources

#712 Cleanup e-puck tools to run RViz alone
  webots_ros2/CHANGELOG.rst
  webots_ros2_epuck/CHANGELOG.rst
  webots_ros2_epuck/launch/robot_launch.py
Labels: bug, cleanup, test sources

#709 Add RGB point cloud
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/CMakeLists.txt
  webots_ros2_driver/include/webots_ros2_driver/plugins/dynamic/Ros2RGBD.hpp
  webots_ros2_driver/src/plugins/dynamic/Ros2RGBD.cpp
  webots_ros2_driver/webots_ros2_rgbd.xml
  webots_ros2_tests/CHANGELOG.rst
  webots_ros2_tests/resource/driver_test.urdf
  webots_ros2_tests/test/test_system_driver.py
Labels: enhancement, test sources

#716 Fix worlds in develop
  webots_ros2_epuck/protos/LegoTallInterval.proto
  webots_ros2_epuck/protos/LegoTallWall.proto
  webots_ros2_epuck/worlds/epuck_world.wbt
  webots_ros2_epuck/worlds/rats_life_benchmark.wbt
  webots_ros2_mavic/worlds/mavic_world.wbt
  webots_ros2_tesla/worlds/tesla_world.wbt
  webots_ros2_tests/worlds/driver_test.wbt
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_tiago/worlds/default.wbt
  webots_ros2_turtlebot/worlds/turtlebot3_burger_example.wbt
  webots_ros2_universal_robot/worlds/robotic_arms.wbt
  webots_ros2_universal_robot/worlds/universal_robot.wbt
Labels: cleanup
