Repository cyberbotics/webots_ros2, pull requests merged in 2023-01, with the labels that each got.

#577 Fix missing gitignore sync
  scripts/sync_controller_lib.sh
Labels: bug, libcontroller sync

#584 Fix naming of ros2_control hardware type
  webots_ros2_control/CMakeLists.txt
  webots_ros2_control/src/Ros2Control.cpp
Labels: bug

#587 Revert E-puck name to `e-puck`
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_epuck/worlds/epuck_world.wbt
  webots_ros2_epuck/worlds/rats_life_benchmark.wbt
Labels: cleanup

#578 Replace macOS Docker installation by UTM Virtual Machine
  webots_ros2_driver/scripts/webots_tcp_client.py
  webots_ros2_driver/webots_ros2_driver/utils.py
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
Labels: enhancement

#596 Remove documentation workflow
  .github/workflows/documentation.yml
Labels: cleanup

#594 Drop support for galactic
  .github/workflows/test.yml
  .github/workflows/test_develop.yml
  scripts/ci_after_init.bash
  webots_ros2/CHANGELOG.rst
  webots_ros2_control/CMakeLists.txt
  webots_ros2_control/include/webots_ros2_control/Ros2ControlSystem.hpp
  webots_ros2_control/src/Ros2Control.cpp
  webots_ros2_control/src/Ros2ControlSystem.cpp
  webots_ros2_driver/CMakeLists.txt
  webots_ros2_driver/src/Driver.cpp
  webots_ros2_driver/src/plugins/static/Ros2Camera.cpp
  webots_ros2_tests/test/test_system_tiago.py
  webots_ros2_tests/test/test_system_turtlebot_tutorial_navigation.py
  webots_ros2_tests/test/test_system_turtlebot_tutorial_slam.py
Labels: cleanup

#598 Merge `master` into `develop`
  .github/workflows/documentation.yml
  .github/workflows/test.yml
  .github/workflows/test_develop.yml
  scripts/ci_after_init.bash
  scripts/sync_controller_lib.sh
  webots_ros2/CHANGELOG.rst
  webots_ros2/package.xml
  webots_ros2/setup.py
  webots_ros2_control/CHANGELOG.rst
  webots_ros2_control/CMakeLists.txt
  webots_ros2_control/include/webots_ros2_control/Ros2ControlSystem.hpp
  webots_ros2_control/package.xml
  webots_ros2_control/src/Ros2Control.cpp
  webots_ros2_control/src/Ros2ControlSystem.cpp
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/CMakeLists.txt
  webots_ros2_driver/include/webots_ros2_driver/plugins/static/Ros2Camera.hpp
  webots_ros2_driver/package.xml
  webots_ros2_driver/scripts/webots_tcp_client.py
  webots_ros2_driver/src/Driver.cpp
  webots_ros2_driver/src/plugins/static/Ros2Camera.cpp
  webots_ros2_driver/webots/projects/default/libraries/vehicle/java/.gitignore
  webots_ros2_driver/webots_ros2_driver/ros2_supervisor.py
  webots_ros2_driver/webots_ros2_driver/utils.py
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
  webots_ros2_epuck/CHANGELOG.rst
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_epuck/package.xml
  webots_ros2_epuck/setup.py
  webots_ros2_epuck/worlds/epuck_world.wbt
  webots_ros2_importer/package.xml
  webots_ros2_importer/setup.py
  webots_ros2_mavic/package.xml
  webots_ros2_mavic/setup.py
  webots_ros2_msgs/CMakeLists.txt
  webots_ros2_msgs/package.xml
  webots_ros2_msgs/srv/SpawnNodeFromString.srv
  webots_ros2_tesla/package.xml
  webots_ros2_tesla/setup.py
  webots_ros2_tests/package.xml
  webots_ros2_tests/setup.py
  webots_ros2_tests/test/test_system_tiago.py
  webots_ros2_tests/test/test_system_turtlebot_tutorial_navigation.py
  webots_ros2_tests/test/test_system_turtlebot_tutorial_slam.py
  webots_ros2_tiago/package.xml
  webots_ros2_tiago/setup.py
  webots_ros2_turtlebot/package.xml
  webots_ros2_turtlebot/setup.py
  webots_ros2_universal_robot/package.xml
  webots_ros2_universal_robot/setup.py
Labels: synchronization
