Repository cyberbotics/webots_ros2, pull requests merged in 2023-02, with the labels that each got.

#612 Fix macOS local assets with relative URLs
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
Labels: bug, test sources

#616 Optional Ros2 Supervisor
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
  webots_ros2_epuck/CHANGELOG.rst
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_mavic/CHANGELOG.rst
  webots_ros2_mavic/launch/robot_launch.py
  webots_ros2_tesla/CHANGELOG.rst
  webots_ros2_tesla/launch/robot_launch.py
  webots_ros2_tiago/CHANGELOG.rst
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_turtlebot/CHANGELOG.rst
  webots_ros2_turtlebot/launch/robot_launch.py
  webots_ros2_universal_robot/CHANGELOG.rst
  webots_ros2_universal_robot/launch/multirobot_launch.py
  webots_ros2_universal_robot/launch/robot_launch/robot_world_launch.py
Labels: enhancement, test sources

#610 Fix URDF spawner on macOS and WSL
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/webots_ros2_driver/ros2_supervisor.py
  webots_ros2_driver/webots_ros2_driver/urdf_spawner.py
  webots_ros2_epuck/CHANGELOG.rst
  webots_ros2_mavic/CHANGELOG.rst
  webots_ros2_tesla/CHANGELOG.rst
  webots_ros2_tiago/CHANGELOG.rst
  webots_ros2_turtlebot/CHANGELOG.rst
  webots_ros2_universal_robot/CHANGELOG.rst
  webots_ros2_universal_robot/resource/Universal_Robots_ROS2_Driver/ur_description/config/ur5e/visual_parameters.yaml
  webots_ros2_universal_robot/resource/robotiq/robotiq_3f_gripper_visualization/cfg/robotiq-3f-gripper_articulated_macro.xacro
  webots_ros2_universal_robot/resource/robotiq/robotiq_3f_gripper_visualization/cfg/robotiq-3f-gripper_finger_articulated_macro.xacro
Labels: bug, test sources

#633 Fix CI tests
  webots_ros2_tests/test/test_system_driver.py
Labels: bug, test sources

#630 Sync master with develop
  webots_ros2/CHANGELOG.rst
  webots_ros2/package.xml
  webots_ros2/setup.py
  webots_ros2_control/package.xml
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/package.xml
  webots_ros2_driver/webots_ros2_driver/ros2_supervisor.py
  webots_ros2_driver/webots_ros2_driver/urdf_spawner.py
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
  webots_ros2_epuck/CHANGELOG.rst
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_epuck/package.xml
  webots_ros2_epuck/setup.py
  webots_ros2_importer/package.xml
  webots_ros2_importer/setup.py
  webots_ros2_mavic/CHANGELOG.rst
  webots_ros2_mavic/launch/robot_launch.py
  webots_ros2_mavic/package.xml
  webots_ros2_mavic/setup.py
  webots_ros2_msgs/package.xml
  webots_ros2_tesla/CHANGELOG.rst
  webots_ros2_tesla/launch/robot_launch.py
  webots_ros2_tesla/package.xml
  webots_ros2_tesla/setup.py
  webots_ros2_tests/package.xml
  webots_ros2_tests/setup.py
  webots_ros2_tests/test/test_system_driver.py
  webots_ros2_tiago/CHANGELOG.rst
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_tiago/package.xml
  webots_ros2_tiago/setup.py
  webots_ros2_turtlebot/CHANGELOG.rst
  webots_ros2_turtlebot/launch/robot_launch.py
  webots_ros2_turtlebot/package.xml
  webots_ros2_turtlebot/setup.py
  webots_ros2_universal_robot/CHANGELOG.rst
  webots_ros2_universal_robot/launch/multirobot_launch.py
  webots_ros2_universal_robot/launch/robot_launch/robot_world_launch.py
  webots_ros2_universal_robot/package.xml
  webots_ros2_universal_robot/resource/Universal_Robots_ROS2_Driver/ur_description/config/ur5e/visual_parameters.yaml
  webots_ros2_universal_robot/resource/robotiq/robotiq_3f_gripper_visualization/cfg/robotiq-3f-gripper_articulated_macro.xacro
  webots_ros2_universal_robot/resource/robotiq/robotiq_3f_gripper_visualization/cfg/robotiq-3f-gripper_finger_articulated_macro.xacro
  webots_ros2_universal_robot/setup.py
Labels: test sources

#629 Update sync_controller_lib.sh to copy version.txt
  scripts/sync_controller_lib.sh
Labels: enhancement

#634 Copy version.txt to libcontroller in master
  scripts/sync_controller_lib.sh
Labels: enhancement

#636 Rename gyro variables to velocity
  webots_ros2_mavic/webots_ros2_mavic/mavic_driver.py
Labels: cleanup

#640 Temporarily fix `diff_drive controller` bad variable name
  webots_ros2_epuck/resource/ros2_control.yml
  webots_ros2_tiago/resource/ros2_control.yml
  webots_ros2_turtlebot/resource/ros2control.yml
Labels: bug

#641 Restore tiago and epuck_tools tests
  scripts/ci_after_init.bash
  webots_ros2_tests/test/test_system_epuck_with_tools.py
  webots_ros2_tests/test/test_system_tiago.py
  webots_ros2_tiago/launch/robot_launch.py
Labels: test sources

#639 Adding port parameter and usage of webots world project file to launcher.py
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/webots_ros2_driver/utils.py
  webots_ros2_driver/webots_ros2_driver/webots_launcher.py
Labels: enhancement, test sources
