Repository cyberbotics/webots_ros2, pull requests merged in 2023-05, with the labels that each got.

#720 Fix nightly tests on develop branch
  .github/workflows/test_develop.yml
Labels: bug

#722 Calculate vertical fov according to https://www.cyberbotics.com/doc/r…
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/src/plugins/static/Ros2RangeFinder.cpp
Labels: bug, test sources

#724 Merge master into develop
  webots_ros2/CHANGELOG.rst
  webots_ros2_importer/CHANGELOG.rst
  webots_ros2_importer/webots_ros2_importer/urdf2proto.py
  webots_ros2_importer/webots_ros2_importer/xacro2proto.py
Labels: synchronization, test sources

#729 Backport CI fix to develop
  webots_ros2_universal_robot/webots_ros2_universal_robot/follow_joint_trajectory_client.py
Labels: synchronization

#737 Clear unused devices in TIAGo example
  webots_ros2_tiago/worlds/.default.wbproj
  webots_ros2_tiago/worlds/default.wbt
Labels: cleanup, test sources

#738 Backport TIAGo cleanup to develop
  webots_ros2_tiago/worlds/.default.wbproj
  webots_ros2_tiago/worlds/default.wbt
Labels: cleanup

#751 Merge master into develop
  scripts/sync_controller_lib.sh
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/src/Driver.cpp
  webots_ros2_driver/src/plugins/static/Ros2RangeFinder.cpp
  webots_ros2_driver/webots_ros2_driver/wait_for_controller_connection.py
  webots_ros2_epuck/CHANGELOG.rst
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_tiago/CHANGELOG.rst
  webots_ros2_tiago/launch/robot_bringup_launch.py
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_turtlebot/CHANGELOG.rst
  webots_ros2_turtlebot/launch/robot_launch.py
  webots_ros2_universal_robot/CHANGELOG.rst
  webots_ros2_universal_robot/launch/multirobot_launch.py
Labels: synchronization, test sources

#746 Feature WebotsController node
  webots_ros2/CHANGELOG.rst
  webots_ros2_driver/CHANGELOG.rst
  webots_ros2_driver/CMakeLists.txt
  webots_ros2_driver/include/webots_ros2_driver/WebotsNode.hpp
  webots_ros2_driver/src/PythonPlugin.cpp
  webots_ros2_driver/src/WebotsNode.cpp
  webots_ros2_driver/webots_ros2_driver/utils.py
  webots_ros2_driver/webots_ros2_driver/webots_controller.py
  webots_ros2_epuck/CHANGELOG.rst
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_mavic/CHANGELOG.rst
  webots_ros2_mavic/launch/robot_launch.py
  webots_ros2_tesla/CHANGELOG.rst
  webots_ros2_tesla/launch/robot_launch.py
  webots_ros2_tests/CHANGELOG.rst
  webots_ros2_tests/test/test_system_driver.py
  webots_ros2_tiago/CHANGELOG.rst
  webots_ros2_tiago/launch/robot_bringup_launch.py
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_turtlebot/CHANGELOG.rst
  webots_ros2_turtlebot/launch/robot_launch.py
  webots_ros2_universal_robot/CHANGELOG.rst
  webots_ros2_universal_robot/launch/multirobot_launch.py
  webots_ros2_universal_robot/launch/robot_launch/robot_nodes_launch.py
Labels: enhancement, test sources

#756 Drop Foxy support
  .github/workflows/test.yml
  .github/workflows/test_develop.yml
  scripts/ci_after_init.bash
  scripts/ci_before_init_embed.bash
  webots_ros2/CHANGELOG.rst
  webots_ros2_control/CMakeLists.txt
  webots_ros2_control/include/webots_ros2_control/Ros2Control.hpp
  webots_ros2_control/include/webots_ros2_control/Ros2ControlSystem.hpp
  webots_ros2_control/include/webots_ros2_control/Ros2ControlSystemInterface.hpp
  webots_ros2_control/src/Ros2Control.cpp
  webots_ros2_control/src/Ros2ControlSystem.cpp
  webots_ros2_driver/CMakeLists.txt
  webots_ros2_driver/include/webots_ros2_driver/plugins/static/Ros2Camera.hpp
  webots_ros2_driver/src/Driver.cpp
  webots_ros2_driver/src/plugins/static/Ros2Camera.cpp
  webots_ros2_epuck/launch/robot_launch.py
  webots_ros2_tesla/webots_ros2_tesla/lane_follower.py
  webots_ros2_tests/test/test_system_epuck_with_tools.py
  webots_ros2_tests/test/test_system_tiago.py
  webots_ros2_tests/test/test_system_turtlebot_tutorial_navigation.py
  webots_ros2_tests/test/test_system_turtlebot_tutorial_slam.py
  webots_ros2_tiago/launch/robot_launch.py
  webots_ros2_turtlebot/launch/robot_launch.py
  webots_ros2_universal_robot/launch/multirobot_launch.py
  webots_ros2_universal_robot/launch/robot_launch/robot_nodes_launch.py
Labels: cleanup
